### PR TITLE
fix: configurable changelog url

### LINKED ISSUE #2419: use latest internal version, after one click "what's new"button, and it go to Github 404 page, back to client, the button has disappeared. ​
### What happened?

use the latest internal version, after one click "what's new"button, and it go to Github 404 page, back to client, the button has disappeared. ​

### Version

macOS x64

### What browsers are you seeing the problem on?

Chrome, Other

### Relevant log output

_No response_

### Anything else?

hope can be fixed before tmr beta launch

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by pengx17**
also fix #2419

### CODE REVIEW

File: packages/component/src/components/app-sidebar/app-updater-button/index.tsx [hunk 1]
```diff
@@ -79,10 +73,19 @@ export function AppUpdaterButton({ className, style }: AddPageButtonProps) {
...
+          } else {
+            window.open(
+              `https://github.com/toeverything/AFFiNE/releases/tag/v${currentVersion}`,
+              '_blank'
+            );
+          }
+        } else if (currentChangelogUnread) {
+          window.open(config.changelogUrl, '_blank');
+        } else {
+          // do nothing since we will not get here
```
Comment (himself65) [inline packages/component/src/components/app-sidebar/app-updater-button/index.tsx]: `throw new Error('unreachable')` is better

**Review by Himself65 — CHANGES_REQUESTED** [review]

**Review by Himself65 — DISMISSED** [review]

**Review by Himself65 — APPROVED** [review]
