### PR TITLE
fix: show up image menu option

### LINKED ISSUE #459: [bug]: Can not show image option
### Describe the bug

Can not show image option

### To Reproduce

1. write down  '/'
2. choose image option
3. click the image button

### Screenshots

image

### Expected behavior

open the image option window

### Platform

MacOS

### Browser

Chrome

### Additional context

Just see the video information below 
https://jam.dev/c/a494e4b2-fd13-4cef-88e8-e63d76b7c7c1

### PR DESCRIPTION
**Pull request by DiamondThree**
fix #459

### CODE REVIEW

**Review by doodlewind — APPROVED** [review]

File: libs/components/editor-blocks/src/components/upload/upload.tsx [hunk 1]
```diff
@@ -36,8 +36,9 @@ interface Props {
 }
 const styles: SxProps = {
     position: 'absolute',
-    width: '600px',
-    zIndex: 99,
+    width: '70%',
+    // maxWidth:'100%',
+    zIndex: 999,
```
Comment (lawvs) [inline libs/components/editor-blocks/src/components/upload/upload.tsx:41]: Why `999`?

**Review by lawvs — APPROVED** [review]
