### PR TITLE
fix: make server guid consistent

### LINKED ISSUE #4132: inconstant guid in server side
There are different formats in the database 

- `${workspaceId}` (uuid)
- `${workspaceId}:space:${pageId}` (uuid:space:nanoid)
- `space:${pageId}` (space:nanoid)

The reason is server will use `uuidv4` as the id generator, but in the frontend will use `nanoid` with `${workspaceId}:space:` as the prefix.

This might cause the SQL table's primary key inconsistent, and hard to lookup the document because there are three types of id for some reason.

What's more, there already some issues in the existing codespace.

Example:
https://github.com/toeverything/AFFiNE/blob/4f97ea8a5d7cda629e6d17345d74a017b18bfcf5/apps/server/src/modules/workspaces/permission.ts#L52-L55

We need to cralify the guid with same format in both frontend and backend

### PR DESCRIPTION
**Pull request by forehalo**
close #4132
walkaround for #4338

### CODE REVIEW

File: apps/server/src/modules/doc/manager.ts [hunk 1]
```diff
@@ -357,4 +367,55 @@ export class DocManager implements OnModuleInit, OnModuleDestroy {
...
+              id_workspaceId: {
+                id: doc.id,
+                workspaceId: doc.workspaceId,
+              },
+            },
+            data: {
+              id: parsed.id,
+            },
+          });
+        }
```
Comment (darkskygit) [inline apps/server/src/modules/doc/manager.ts:415]: put in a transaction

**Review by himself65 — COMMENTED** [review]
I think we should merge this all together

https://github.com/toeverything/blocksuite/pull/4747

File: apps/server/src/modules/doc/manager.ts (hunk 1 above)
Comment (forehalo) [reply apps/server/src/modules/doc/manager.ts:415]: The delete statement is meaning to delete the unexpected data with wrong guid, like we fix `${ws}:space:${id}` to `space:${id}`, but the `space:${id}` should never exist before in the database, so in this way we could avoid primary key conflict.

Comment (forehalo) [reply apps/server/src/modules/doc/manager.ts:415]: I checked my local database with some test workspace, somehow both `${ws}:space:${id}` and `space:${id}` existed, which is impossible in our codebase because guid itself is consistent once the doc is ever created.

File: apps/core/src/hooks/affine/use-is-shared-page.ts [hunk 2]
```diff
@@ -31,18 +31,14 @@ export function useIsSharedPage(
       (enable: boolean) => {
         // todo: push notification
         if (enable) {
-          enableSharePage({
-            workspaceId,
-            pageId,
-          })
+          enableSharePage({ docId: `${workspaceId}:space:${pageId}` })
```
Comment (forehalo) [inline apps/core/src/hooks/affine/use-is-shared-page.ts:34]: https://github.com/toeverything/blocksuite/pull/4747 carefully bump blocksuite the next time @himself65

**Review by himself65 — COMMENTED** [review]
blocksuite side already merges the id generator breaking change. I wonder if we should also do some compatible in this PR

**Comment by forehalo** [comment]
> blocksuite side already merges the id generator breaking change. I wonder if we should also do some compatible in this PR

done

**Review by Brooooooklyn — APPROVED** [review]

**Review by darkskygit — APPROVED** [review]

**Review by Brooooooklyn — APPROVED** [review]
