### PR TITLE
fix: create page with title

### LINKED ISSUE #1448: Can't create page with title

### PR DESCRIPTION
**Pull request by JimmFly**
Close #1448

### CODE REVIEW

File: apps/web/src/components/pure/quick-search-modal/Footer.tsx [hunk 1]
```diff
@@ -1,4 +1,5 @@
 import { useTranslation } from '@affine/i18n';
+import { PageBlockModel } from '@blocksuite/blocks';
```
Comment (himself65) [inline apps/web/src/components/pure/quick-search-modal/Footer.tsx]:
```suggestion
import type { PageBlockModel } from '@blocksuite/blocks';
```

**Comment by himself65** [comment]
Fix DeepScan

**Review by himself65 — APPROVED** [review]
