### PR TITLE
fix(core): set state isLoading to false after email changing is confirmed

### LINKED ISSUE #9822: ​Changing email will lead to a blank page.
### What happened?

Steps to reproduce:
- Open settings
- Change email

Will observe a blank page.

https://github.com/user-attachments/assets/e3e63082-9045-4726-9fb4-eb274477f9ff

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [ ] Yes

### Relevant log output

```shell

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by UNIDY2002**
Otherwise, a fallback screen will always be displayed.

Should fix #9822

### CODE REVIEW

File: packages/frontend/core/src/desktop/pages/auth/confirm-change-email.tsx [hunk 1]
```diff
@@ -41,6 +41,7 @@ export const ConfirmChangeEmail: FC<{
           }
           throw err;
         });
+      setIsLoading(false);
```
Comment (pengx17) [inline packages/frontend/core/src/desktop/pages/auth/confirm-change-email.tsx]: may put it in  `.final` instead

**Review by pengx17 — APPROVED** [review]

**Review by Brooooooklyn — APPROVED** [review]
