### PR TITLE
fix(core): back home botton has no reaction 

### LINKED ISSUE #4201: There is no reaction upon clicking the Back Home button on the 404 Page.
image

@xell

### PR DESCRIPTION
**Pull request by joooye34**
close #4201 

The back to last workspace logic in 404 page just been removed, because index page will do this more safely.

There have some others logic should be improved but not this commit:
1. no 400 exception page, all in 404
2. 404 should have search params to know what resource not found and what page from

### CODE REVIEW

**Review by pengx17 — APPROVED** [review]

File: apps/core/src/pages/404.tsx [hunk 1]
```diff
@@ -26,22 +25,14 @@ export const StyledContainer = styled('div')(() => {
...
-        onClick={() => {
-          const id = localStorage.getItem('last_workspace_id');
-          if (id) {
-            jumpToSubPath(id, WorkspaceSubPath.ALL);
-          } else {
-            jumpToIndex();
-          }
-        }}
-      >
+      <Button onClick={() => jumpToIndex()}>
```
Comment (himself65) [inline apps/core/src/pages/404.tsx]: useCallback

**Review by himself65 — CHANGES_REQUESTED** [review]

**Review by himself65 — APPROVED** [review]

File: apps/core/src/pages/404.tsx (hunk 1 above)
Comment (joooye34) [reply apps/core/src/pages/404.tsx]: I have seen lint error in CI, but why my local lint is successful.

Comment (joooye34) [reply apps/core/src/pages/404.tsx]: oh, u commit a patch to improve the code
