### PR TITLE
fix: use absolute path in gql client

### LINKED ISSUE #5448: Image uploaded from client can't collaborate with others
### What happened?

1. Upload image in client
image

2. Open web page

image

We can see image load failed.

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by darkskygit**
fix #5448

### CODE REVIEW

**Comment by darkskygit** [comment]
Current dependencies on/for this PR:
* `canary`
  * **PR #5454** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5454?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/toeverything/AFFiNE/5454?utm_source=stack-comment).

**Review by pengx17 — APPROVED** [review]

File: packages/frontend/graphql/src/index.ts [hunk 1]
```diff
@@ -6,4 +6,12 @@ import '@affine/env/global';
 
 import { gqlFetcherFactory } from './fetcher';
 
-export const fetcher = gqlFetcherFactory('/graphql');
+export function getBaseUrl(): string {
+  if (environment.isDesktop) {
```
Comment (EYHN) [inline packages/frontend/graphql/src/index.ts:13]: maybe need `setupGlobal()`

**Review by EYHN — APPROVED** [review]
