### PR TITLE
fix(electron): respect locale for spellchecker

### LINKED ISSUE #8837: ​Unable to set the document spellcheck language
### What happened?

I'm using the official Electron-based Linux app which is distributed as an AppImage.

The spellcheck can be enabled in the settings. I set the UI language to English and cleared the locale environment. However, the document spellcheck language seems to be picked up from the desktop environment somehow. That is confusing and wrong, and I don't know how to set it properly. It seems that the spellcheck is a built-in feature of electron that needs to be configured.

I propose to implement at least one of the following (from less to more preferred, in my opinion):

1. Pick up the Linux locale variables or describe the mechanism to set the spellcheck language, if there is no setting.
2. Set the spellcheck language in the settings dialog explicitly
3. Set a language tag for each document that is respected by the spellcheck

Thanks!

### PR DESCRIPTION
**Pull request by pengx17**
may fix #8837.
fix AF-1712

MacOS automatically do spellcheck based on given text. This only works for Win/Linux.

### CODE REVIEW

**Comment by pengx17** [comment]
* **#8844** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/8844?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/8844?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/frontend/apps/electron/src/main/ui/handlers.ts [hunk 1]
```diff
@@ -220,4 +221,14 @@ export const uiHandlers = {
     app.relaunch();
     app.quit();
   },
+  onLanguageChange: async (e, language: string) => {
+    // only works for win/linux
```
Comment (forehalo) [inline packages/frontend/apps/electron/src/main/ui/handlers.ts:225]: any reason or read more link?

Comment (forehalo) [reply packages/frontend/apps/electron/src/main/ui/handlers.ts:225]: I find it it electron docs, better quote it https://www.electronjs.org/docs/latest/tutorial/spellchecker#how-to-set-the-languages-the-spellchecker-uses

**Review by forehalo — APPROVED** [review]
