### PR TITLE
fix: title behavior on BlockSuite editor

### LINKED ISSUE #1261: Unhandle Runtime error `Error: yText must be attached to a Y.Doc`
image

Run the code in the master branch by using pnpm dev, and access 127.0.0.1:8080 in browser

### LINKED ISSUE #1266: virgo title unexpected behavior when new page
https://user-images.githubusercontent.com/14026360/222447006-366c7ee3-1abd-43e8-948d-dae4af370fcb.mp4

### PR DESCRIPTION
**Pull request by himself65**
Fixes https://github.com/toeverything/AFFiNE/issues/1261
Fixes https://github.com/toeverything/AFFiNE/issues/1266

### CODE REVIEW

File: apps/web/src/components/page-detail-editor.tsx [hunk 1]
```diff
@@ -57,6 +57,7 @@ export const PageDetailEditor: React.FC<PageDetailEditorProps> = ({
         style={{
           height: 'calc(100% - 60px)',
         }}
+        key={pageId}
```
Comment (himself65) [inline apps/web/src/components/page-detail-editor.tsx:60]: this is a hack, need to remove /cc @Flrande

**Review by darkskygit — APPROVED** [review]

**Comment by himself65** [comment]
https://github.com/toeverything/blocksuite/commit/718fc73670cd5b4b3329982675859b19672697a1

**Review by darkskygit — APPROVED** [review]
