### PR TITLE
fix: dark mode export PDF leaves margin and notification

### LINKED ISSUE #2979: Dark mode export PDF leaves margin
Dark mode export PDF leaves margin

Image

### PR DESCRIPTION
**Pull request by zuoxiaodong0815**
close #2979

### CODE REVIEW

File: packages/component/src/components/page-list/operation-menu-items/export.tsx [hunk 1]
```diff
@@ -38,17 +38,17 @@ const ExportToPdfMenuItem = ({
...
             type: 'success',
           });
         })
         .catch(err => {
           console.error(err);
           setPushNotification({
             key: 'export-to-pdf',
-            title: 'export',
-            message: 'Export error',
+            title: 'Export failed due to an unexpected error',
```
Comment (himself65) [inline packages/component/src/components/page-list/operation-menu-items/export.tsx]: i18n needed

Comment (zuoxiaodong0815) [reply packages/component/src/components/page-list/operation-menu-items/export.tsx]: Already added i18n
