### PR TITLE
fix: read permission for subpage

### LINKED ISSUE #4335: When logged into an AFFiNE account on the web version, accessing a public link should not display 404 page
image

The expected result is that public links can be accessed normally regardless of whether an AFFiNE account is logged in or not.

### PR DESCRIPTION
**Pull request by darkskygit**
fix #4335

### CODE REVIEW

File: apps/server/src/modules/workspaces/permission.ts [hunk 1]
```diff
@@ -47,37 +47,38 @@ export class PermissionService {
...
-    } else {
-      // check if this is a public workspace
-      const count = await this.prisma.workspace.count({
-        where: { id: ws, public: true },
-      });
-      if (count > 0) {
-        return true;
-      }
+      const hasPermission = await this.tryCheck(ws, user);
+      if (hasPermission) return true;
```
Comment (Brooooooklyn) [inline apps/server/src/modules/workspaces/permission.ts:51]:
```suggestion
      return this.tryCheck(ws, user)
```

Comment (darkskygit) [reply apps/server/src/modules/workspaces/permission.ts:51]: if user not have full workspace permission, we need continue check sub page permission

**Review by Brooooooklyn — APPROVED** [review]
