### PR TITLE
fix(server): redirect to setup page if not initialized

### LINKED ISSUE #7833: Cannot get Affine server to run properly
### What happened?

Following these instructions: https://docs.affine.pro/docs/self-host-affine results in errors when running the compose command. The terms AFFINE_ADMIN_EMAIL and AFFINE_ADMIN_PASSWORD are not recognized as commands. I tried specifying them inside the compose.yaml file, instead of the variables, then the system goes up, but then I get "Failed to send email. Please try again." upon entering username...

I tried pruning, I tried re-pulling fresh containers, no effect.

I selected wrong distribution version because right one isn't available.

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome, Firefox

### Are you self-hosting?

- [x] Yes

### Relevant log output

_No response_

### Anything else?

Using Docker 4.33.1 on Windows 10.

### PR DESCRIPTION
**Pull request by forehalo**
close https://github.com/toeverything/AFFiNE/issues/7833

### CODE REVIEW

**Comment by forehalo** [comment]
* **#7875** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/7875?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @forehalo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by darkskygit — APPROVED** [review]

File: packages/frontend/admin/src/modules/common.ts [hunk 1]
```diff
@@ -15,6 +15,14 @@ export const useServerConfig = () => {
   return data.serverConfig;
 };
 
+export const useRevalidateServerConfig = () => {
+  const revalidate = useMutateQueryResource();
+
+  return () => {
+    revalidate(adminServerConfigQuery);
```
Comment (pengx17) [inline packages/frontend/admin/src/modules/common.ts]: floating promise?

**Review by pengx17 — APPROVED** [review]

File: packages/frontend/admin/src/modules/common.ts (hunk 1 above)
Comment (forehalo) [reply packages/frontend/admin/src/modules/common.ts]: I hate swr
